import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-container": "#474746",
        "outline-variant": "#464554",
        "surface-container-high": "#2a2a2a",
        "tertiary-fixed": "#ffdcc5",
        "primary-fixed-dim": "#c0c1ff",
        "inverse-surface": "#e5e2e1",
        "on-secondary-container": "#b7b5b4",
        "tertiary-container": "#d97721",
        "surface": "#131313",
        "secondary-fixed-dim": "#c8c6c5",
        "on-secondary-fixed": "#1b1c1c",
        "surface-container-highest": "#353534",
        "surface-container-lowest": "#0e0e0e",
        "on-tertiary-container": "#452000",
        "on-secondary": "#303030",
        "on-tertiary-fixed": "#301400",
        "secondary": "#c8c6c5",
        "surface-container-low": "#1c1b1b",
        "surface-tint": "#c0c1ff",
        "error": "#ffb4ab",
        "surface-variant": "#353534",
        "surface-dim": "#131313",
        "inverse-primary": "#494bd6",
        "error-container": "#93000a",
        "on-tertiary-fixed-variant": "#703700",
        "tertiary": "#ffb783",
        "surface-container": "#201f1f",
        "outline": "#908fa0",
        "on-primary-container": "#0d0096",
        "primary": "#c0c1ff",
        "on-primary-fixed": "#07006c",
        "primary-container": "#8083ff",
        "surface-bright": "#3a3939",
        "on-surface": "#e5e2e1",
        "on-background": "#e5e2e1",
        "on-primary": "#1000a9",
        "inverse-on-surface": "#313030",
        "on-tertiary": "#4f2500",
        "tertiary-fixed-dim": "#ffb783",
        "secondary-fixed": "#e4e2e1",
        "on-surface-variant": "#c7c4d7",
        "on-secondary-fixed-variant": "#474746",
        "on-primary-fixed-variant": "#2f2ebe",
        "background": "#131313",
        "on-error-container": "#ffdad6",
        "on-error": "#690005",
        "primary-fixed": "#e1e0ff",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        headline: ["Satoshi", "Inter", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
        manrope: ["Satoshi", "Inter", "sans-serif"],
      },
    },
  },
};

export default config;